version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: "tensorflow/tensorflow:latest"
    steps:
      - checkout
      - python/load-cache
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - python/save-cache
      - run:
          command: pwd
          name: Print location
      - run:
          command: cd docs/ && make html && cd ..
          name: Build docs
      - run:
          command: cp -a docs/_build/html/* docs/
          name: Copy docs
      - run:
          command: python -m pytest -v --cov=kaldo kaldo/tests/
          name: Test
workflows:
  main:
    jobs:
      - build-and-test
