version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: "tensorflow/tensorflow:latest"
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
            command: pwd && ls -la
            name: Print location
      - run:
          command: sh docs/install_pandoc.sh
          name: Install pandoc
      - run:
          command: cd docs/ && make html && cd ..
          name: Build docs
      - run:
          command: cp -a docs/_build/html/* docs/
          name: Copy docs
      - run:
          command: python -m pytest -v --cov=kaldo kaldo/tests/
          name: Test
workflows:
  main:
    jobs:
      - build-and-test
