version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: "tensorflow/tensorflow:latest"
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pytest -v --cov=kaldo kaldo/tests/
          name: Test
  docs-build:
    docker:
      - image: "continuumio/miniconda3:4.6.14"
    steps:
      - checkout
      - run:
          name: Add pip
          command: conda install pip
      - run:
          name: Add pandoc
          command: conda install -c conda-forge pandoc
      - run:
          name: Add make
          command: conda install make
      - run:
          name: Add psutil
          command: conda install psutil>=5.7.2
      - run:
          name: Install docs dependencies
          command: pip install -r docs/doc_requirements.txt
      - run:
          name: Build docs
          command: cd docs/ && make html
      - run:
          name: Create .jekyll
          command: cd docs/_build/ && touch .nojekyll
      - persist_to_workspace:
          root: docs/_build
          paths: html
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: docs/_build
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@klukas.net"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "2e:d6:fb:40:f4:c4:c0:e3:79:f5:53:ad:e0:b4:a5:2a"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --dotfiles --message "[skip ci] Updates" --dist docs/_build/html
workflows:
  main:
    jobs:
      - build-and-test
      - docs-build
      - docs-deploy:
          requires:
            - build-and-test
            - docs-build
          filters:
            branches:
              only: master

