version: 2.1

orbs:
  python: circleci/python@0.2.1

jobs:
  build-and-test:
    docker:
      - image: "tensorflow/tensorflow:latest"
    steps:
      - checkout
      - python/load-cache
      - python/install-deps
      - python/save-cache
      - run:
          command: python -m pytest -v --cov=kaldo kaldo/tests/
          name: Test
workflows:
  main:
    jobs:
      - build-and-test
